const PDFDocument = require('pdfkit');
const { substituteClauses } = require('./clauseSubstitution');

// ─── Design tokens ────────────────────────────────────────────────────────────
const C = {
  navy: '#0F2B5B',   // primary dark
  blue: '#1A56DB',   // accent
  lightBlue: '#EBF2FF',   // section bg tint
  teal: '#0D9488',   // badge / highlight
  gray900: '#111827',
  gray700: '#374151',
  gray500: '#6B7280',
  gray300: '#D1D5DB',
  gray100: '#F3F4F6',
  white: '#FFFFFF',
  green: '#059669',
  amber: '#D97706',
  red: '#DC2626',
};

const FONT = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  oblique: 'Helvetica-Oblique',
};

const PAGE = { width: 595.28, height: 841.89, margin: 50 };
const CONTENT_W = PAGE.width - PAGE.margin * 2;

// ─── Low-level drawing helpers ────────────────────────────────────────────────

/** Filled rectangle */
function rect(doc, x, y, w, h, color) {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

/** Horizontal rule */
function hr(doc, y, color = C.gray300, x = PAGE.margin, w = CONTENT_W) {
  doc.save().moveTo(x, y).lineTo(x + w, y).lineWidth(0.5).strokeColor(color).stroke().restore();
}

/** Text clipped to a width (no built-in truncation in PDFKit) */
function safeText(doc, text, x, y, opts = {}) {
  doc.text(String(text ?? ''), x, y, { lineBreak: false, ...opts });
}

/** Rounded-corner badge */
function badge(doc, label, x, y, bgColor, textColor = C.white) {
  const pad = 6;
  const w = doc.widthOfString(label) + pad * 2;
  doc.save().roundedRect(x, y - 1, w, 14, 3).fill(bgColor).restore();
  doc.save().font(FONT.bold).fontSize(7).fillColor(textColor).text(label, x + pad, y + 1, { lineBreak: false }).restore();
  return w;
}

// ─── Page furniture (header bar + footer) ────────────────────────────────────

function addPageFurniture(doc, pageNum, totalPages, title = 'RENTAL AGREEMENT') {
  const savedY = doc.y;

  // ── White page background — prevents dark-mode PDF viewers inverting the page ──
  rect(doc, 0, 0, PAGE.width, PAGE.height, C.white);

  // ── Top bar ──
  rect(doc, 0, 0, PAGE.width, 36, C.navy);
  doc.save()
    .font(FONT.bold).fontSize(11).fillColor(C.white)
    .text('RentifyPro', PAGE.margin, 12, { lineBreak: false })
    .restore();
  doc.save()
    .font(FONT.regular).fontSize(8).fillColor('#93C5FD')
    .text(title, 0, 14, { align: 'center', lineBreak: false, width: PAGE.width })
    .restore();
  doc.save()
    .font(FONT.regular).fontSize(8).fillColor('#93C5FD')
    .text(`Page ${pageNum} of ${totalPages}`, PAGE.margin, 14, {
      align: 'right', lineBreak: false, width: CONTENT_W,
    })
    .restore();

  // ── Bottom bar ──
  rect(doc, 0, PAGE.height - 28, PAGE.width, 28, C.navy);
  const footer = 'Generated by RentifyPro. Digital signatures are legally binding.';
  const footerW = doc.widthOfString(footer, { font: FONT.regular, size: 7 });
  const footerX = Math.max(PAGE.margin, (PAGE.width - footerW) / 2);
  doc.save()
    .font(FONT.regular).fontSize(7).fillColor('#93C5FD')
    .text(footer, footerX, PAGE.height - 17, { lineBreak: false })
    .restore();

  doc.y = savedY;
}

function finalizeAgreementPagination(doc, title = 'RENTAL AGREEMENT') {
  const range = doc.bufferedPageRange();
  const totalPages = range.count;

  for (let i = range.start + 1; i < range.start + range.count; i++) {
    const pageNum = i + 1;
    doc.switchToPage(i);

    // Repaint only the top bar so the final page counter can include total pages.
    rect(doc, 0, 0, PAGE.width, 36, C.navy);

    doc.save()
      .font(FONT.bold).fontSize(11).fillColor(C.white)
      .text('RentifyPro', PAGE.margin, 12, { lineBreak: false })
      .restore();
    doc.save()
      .font(FONT.regular).fontSize(8).fillColor('#93C5FD')
      .text(title, 0, 14, { align: 'center', lineBreak: false, width: PAGE.width })
      .restore();
    doc.save()
      .font(FONT.regular).fontSize(8).fillColor('#93C5FD')
      .text(`Page ${pageNum} of ${totalPages}`, PAGE.margin, 14, {
        align: 'right', lineBreak: false, width: CONTENT_W,
      })
      .restore();
  }
}

// ─── Section heading ──────────────────────────────────────────────────────────

function sectionHeading(doc, label, y) {
  rect(doc, PAGE.margin, y, CONTENT_W, 24, C.lightBlue);
  doc.save()
    .rect(PAGE.margin, y, 4, 24).fill(C.blue).restore();
  doc.save()
    .font(FONT.bold).fontSize(8.25).fillColor(C.navy)
    .text(label.toUpperCase(), PAGE.margin + 12, y + 7, { lineBreak: false })
    .restore();
  return y + 32;
}

function majorSectionHeading(doc, code, title, subtitle, y) {
  doc.save()
    .font(FONT.bold).fontSize(14).fillColor(C.navy)
    .text(`${code}  ${title}`, PAGE.margin, y, { lineBreak: false })
    .restore();

  y += 19;

  if (subtitle) {
    doc.save()
      .font(FONT.regular).fontSize(8).fillColor(C.gray500)
      .text(subtitle, PAGE.margin, y, { width: CONTENT_W, lineBreak: false })
      .restore();
    y += 12;
  }

  hr(doc, y, C.gray300);
  return y + 12;
}

// ─── Two-column info row ──────────────────────────────────────────────────────

function infoRow(doc, label, value, x, y, colW = CONTENT_W / 2 - 6) {
  doc.save().font(FONT.bold).fontSize(7.5).fillColor(C.gray500)
    .text(label.toUpperCase(), x, y, { lineBreak: false, width: colW })
    .restore();
  doc.save().font(FONT.regular).fontSize(9.5).fillColor(C.gray900)
    .text(String(value ?? '—'), x, y + 10, { lineBreak: false, width: colW })
    .restore();
  return y + 28;
}

// ─── Financial summary table ──────────────────────────────────────────────────

function financialTable(doc, rows, y) {
  const col0 = PAGE.margin;
  const col1 = PAGE.margin + CONTENT_W * 0.65;
  const rowH = 24;

  rows.forEach((row, i) => {
    const bg = row.highlight ? C.lightBlue : (i % 2 === 0 ? C.white : C.gray100);
    rect(doc, col0, y, CONTENT_W, rowH, bg);

    doc.save()
      .font(row.highlight ? FONT.bold : FONT.regular)
      .fontSize(9.5).fillColor(C.gray700)
      .text(row.label, col0 + 10, y + 7, { lineBreak: false })
      .restore();

    doc.save()
      .font(row.highlight ? FONT.bold : FONT.regular)
      .fontSize(9.5).fillColor(row.highlight ? C.navy : C.gray900)
      .text(row.value, col1, y + 7, { lineBreak: false, align: 'right', width: CONTENT_W * 0.35 - 10 })
      .restore();

    y += rowH;
  });

  // bottom border
  hr(doc, y, C.gray300);
  return y + 8;
}

// ─── Signature block ──────────────────────────────────────────────────────────

function signatureBlock(doc, label, person, sigData, signedAt, x, y, blockW, opts = {}) {
  const blockH = opts.blockH || 110;
  const headerH = 24;

  // Box
  doc.save().roundedRect(x, y, blockW, blockH, 7).stroke(C.gray300).restore();

  // Label
  rect(doc, x, y, blockW, headerH, C.navy);
  doc.save().font(FONT.bold).fontSize(8).fillColor(C.white)
    .text(label, x + 10, y + 8, { lineBreak: false })
    .restore();

  let cy = y + headerH + 8;

  if (sigData) {
    try {
      const base64 = sigData.replace(/^data:image\/\w+;base64,/, '');
      const imgBuf = Buffer.from(base64, 'base64');
      const sigW = Math.max(80, blockW - 72);
      const sigH = 24;
      const sigX = x + (blockW - sigW) / 2;
      doc.image(imgBuf, sigX, cy, {
        fit: [sigW, sigH],
        align: 'center',
        valign: 'center',
      });
    } catch (_) {
      doc.save().font(FONT.oblique).fontSize(8).fillColor(C.gray500)
        .text('[Signature image unavailable]', x + 12, cy + 8, { lineBreak: false, width: blockW - 24, align: 'center' })
        .restore();
    }
    cy += 30;
  } else {
    // blank line
    hr(doc, cy + 12, C.gray500, x + 36, blockW - 72);
    cy += 18;
  }

  const metaY = Math.max(cy + 2, y + blockH - 30);

  doc.save().font(FONT.bold).fontSize(8.5).fillColor(C.gray900)
    .text(person?.name || '________________', x + 12, metaY, { lineBreak: false, width: blockW - 24, align: 'center' })
    .restore();

  if (signedAt) {
    doc.save().font(FONT.regular).fontSize(7.5).fillColor(C.gray700)
      .text(`Signed on ${new Date(signedAt).toLocaleString('en-US')}`, x + 12, metaY + 12, {
        lineBreak: false,
        width: blockW - 24,
        align: 'center',
      })
      .restore();
  } else {
    doc.save().font(FONT.regular).fontSize(7.5).fillColor(C.gray700)
      .text('Pending Signature', x + 12, metaY + 12, { lineBreak: false, width: blockW - 24, align: 'center' })
      .restore();
  }
}

// ═════════════════════════════════════════════════════════════════════════════
// AGREEMENT PDF
// ═════════════════════════════════════════════════════════════════════════════

function _buildPDF(doc, agreement, landlord, tenant, property) {
  const fmt = {
    money: n => `$${(n ?? 0).toLocaleString('en-US')}`,
    date: d => d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—',
  };

  const address = property?.address
    ? [property.address.street, property.address.city, property.address.state].filter(Boolean).join(', ')
    : '—';

  // ── We'll do a 2-pass approach: build content first, then we know page count.
  // PDFKit doesn't support total page count natively, so we track manually.
  // We add furniture after each page via the 'pageAdded' event.
  let pageNum = 1;

  // Track page numbers via events
  doc.on('pageAdded', () => { pageNum++; });

  // We'll use a post-process trick: render furniture on every page.
  // Because PDFKit doesn't expose totalPages, we write "Page N" and patch later.
  // For simplicity, we render furniture inline at the start of each page.

  // ════ PAGE 1 — COVER ═══════════════════════════════════════════════════════

  // ── White page background — prevents dark-mode PDF viewers inverting the page ──
  rect(doc, 0, 0, PAGE.width, PAGE.height, C.white);

  // Full navy header banner
  rect(doc, 0, 0, PAGE.width, 180, C.navy);

  // Decorative circle accents
  doc.save().circle(PAGE.width - 60, 40, 70).fillOpacity(0.07).fill(C.white).restore();
  doc.save().circle(PAGE.width - 20, 160, 50).fillOpacity(0.05).fill(C.white).restore();

  // Logo / brand
  doc.save().font(FONT.bold).fontSize(22).fillColor(C.white).fillOpacity(1)
    .text('RentifyPro', PAGE.margin, 36, { lineBreak: false })
    .restore();
  doc.save().font(FONT.regular).fontSize(9).fillColor('#93C5FD')
    .text('Property Management Platform', PAGE.margin, 62, { lineBreak: false })
    .restore();

  // Document title
  doc.save().font(FONT.bold).fontSize(26).fillColor(C.white)
    .text('RESIDENTIAL RENTAL', PAGE.margin, 98, { lineBreak: false })
    .restore();
  doc.save().font(FONT.bold).fontSize(26).fillColor('#60A5FA')
    .text('AGREEMENT', PAGE.margin, 126, { lineBreak: false })
    .restore();

  // Date badge
  const dateStr = `Generated: ${fmt.date(new Date())}`;
  doc.save().font(FONT.regular).fontSize(8).fillColor('#93C5FD')
    .text(dateStr, PAGE.margin, 158, { lineBreak: false })
    .restore();

  // Agreement ID
  doc.save().font(FONT.regular).fontSize(8).fillColor('#93C5FD')
    .text(`Agreement ID: ${agreement._id}`, 0, 158, { align: 'right', lineBreak: false, width: PAGE.width - PAGE.margin })
    .restore();

  let y = 200;

  // ── Parties & Property cards ──
  // Two side-by-side cards
  const cardW = (CONTENT_W - 12) / 2;

  // Landlord card
  rect(doc, PAGE.margin, y, cardW, 80, C.gray100);
  doc.save().rect(PAGE.margin, y, cardW, 80).stroke(C.gray300).restore();
  doc.save().font(FONT.bold).fontSize(7).fillColor(C.blue)
    .text('LANDLORD', PAGE.margin + 10, y + 10, { lineBreak: false })
    .restore();
  doc.save().font(FONT.bold).fontSize(11).fillColor(C.gray900)
    .text(landlord?.name || '—', PAGE.margin + 10, y + 22, { lineBreak: false, width: cardW - 20 })
    .restore();
  doc.save().font(FONT.regular).fontSize(8.5).fillColor(C.gray500)
    .text(landlord?.email || '—', PAGE.margin + 10, y + 38, { lineBreak: false, width: cardW - 20 })
    .restore();
  if (landlord?.phoneNumber) {
    doc.save().font(FONT.regular).fontSize(8.5).fillColor(C.gray500)
      .text(landlord.phoneNumber, PAGE.margin + 10, y + 52, { lineBreak: false, width: cardW - 20 })
      .restore();
  }

  // Tenant card
  const cx2 = PAGE.margin + cardW + 12;
  rect(doc, cx2, y, cardW, 80, C.gray100);
  doc.save().rect(cx2, y, cardW, 80).stroke(C.gray300).restore();
  doc.save().font(FONT.bold).fontSize(7).fillColor(C.teal)
    .text('TENANT', cx2 + 10, y + 10, { lineBreak: false })
    .restore();
  doc.save().font(FONT.bold).fontSize(11).fillColor(C.gray900)
    .text(tenant?.name || '—', cx2 + 10, y + 22, { lineBreak: false, width: cardW - 20 })
    .restore();
  doc.save().font(FONT.regular).fontSize(8.5).fillColor(C.gray500)
    .text(tenant?.email || '—', cx2 + 10, y + 38, { lineBreak: false, width: cardW - 20 })
    .restore();
  if (tenant?.phoneNumber) {
    doc.save().font(FONT.regular).fontSize(8.5).fillColor(C.gray500)
      .text(tenant.phoneNumber, cx2 + 10, y + 52, { lineBreak: false, width: cardW - 20 })
      .restore();
  }

  y += 92;

  // Property card (full width)
  rect(doc, PAGE.margin, y, CONTENT_W, 56, C.lightBlue);
  doc.save().rect(PAGE.margin, y, CONTENT_W, 56).stroke(C.blue).restore();
  doc.save().rect(PAGE.margin, y, 4, 56).fill(C.blue).restore();
  doc.save().font(FONT.bold).fontSize(7).fillColor(C.blue)
    .text('PROPERTY', PAGE.margin + 12, y + 10, { lineBreak: false })
    .restore();
  doc.save().font(FONT.bold).fontSize(11.5).fillColor(C.navy)
    .text(property?.title || '—', PAGE.margin + 12, y + 22, { lineBreak: false, width: CONTENT_W - 24 })
    .restore();
  doc.save().font(FONT.regular).fontSize(8.5).fillColor(C.gray700)
    .text(address, PAGE.margin + 12, y + 38, { lineBreak: false, width: CONTENT_W - 24 })
    .restore();

  y += 68;

  // ── Term summary strip ──
  rect(doc, PAGE.margin, y, CONTENT_W, 48, C.navy);
  const termCols = [
    { label: 'START DATE', value: fmt.date(agreement.term?.startDate) },
    { label: 'END DATE', value: fmt.date(agreement.term?.endDate) },
    { label: 'DURATION', value: `${agreement.term?.durationMonths || '—'} months` },
    { label: 'MONTHLY RENT', value: fmt.money(agreement.financials?.rentAmount) },
  ];
  const colW4 = CONTENT_W / 4;
  termCols.forEach((col, i) => {
    const cx = PAGE.margin + i * colW4 + 12;
    doc.save().font(FONT.bold).fontSize(6.5).fillColor('#93C5FD')
      .text(col.label, cx, y + 10, { lineBreak: false, width: colW4 - 16 })
      .restore();
    doc.save().font(FONT.bold).fontSize(10).fillColor(C.white)
      .text(col.value, cx, y + 22, { lineBreak: false, width: colW4 - 16 })
      .restore();
    if (i < 3) {
      doc.save().moveTo(PAGE.margin + (i + 1) * colW4, y + 8)
        .lineTo(PAGE.margin + (i + 1) * colW4, y + 40)
        .lineWidth(0.5).strokeColor('#1E40AF').stroke().restore();
    }
  });

  y += 60;

  // ════ PAGE 2 — FINANCIAL & TERMS ══════════════════════════════════════════
  doc.addPage();
  addPageFurniture(doc, 2, '—');
  y = 56;

  // ── Financials section ──
  y = majorSectionHeading(
    doc,
    '01',
    'FINANCIAL TERMS',
    'Core rent, deposit, and move-in financial obligations.',
    y
  );

  const petDeposit = agreement.petPolicy?.allowed ? (agreement.petPolicy?.deposit || 0) : 0;
  const maintenanceFee = property?.financials?.maintenanceFee || 0;
  const finRows = [
    { label: 'Monthly Rent', value: fmt.money(agreement.financials?.rentAmount) },
    { label: 'Security Deposit', value: fmt.money(agreement.financials?.depositAmount) },
    { label: 'Maintenance Fee', value: fmt.money(maintenanceFee) },
    { label: 'Late Fee', value: fmt.money(agreement.financials?.lateFeeAmount || 0) },
    { label: 'Late Fee Grace Period', value: `${agreement.financials?.lateFeeGracePeriodDays || 5} days` },
    ...(petDeposit > 0 ? [{ label: 'Pet Deposit (non-refundable)', value: fmt.money(petDeposit) }] : []),
    {
      label: 'Total Move-In Cost',
      value: fmt.money((agreement.financials?.rentAmount || 0) + (agreement.financials?.depositAmount || 0) + maintenanceFee + petDeposit),
      highlight: true,
    },
  ];
  y = financialTable(doc, finRows, y);
  y += 12;

  // ── Utilities & Policies section ──
  y = majorSectionHeading(
    doc,
    '02',
    'UTILITIES & POLICIES',
    'Utility coverage, pet policy, and lease policy conditions.',
    y
  );

  const col1x = PAGE.margin;
  const col2x = PAGE.margin + CONTENT_W / 2 + 6;
  const halfW = CONTENT_W / 2 - 6;

  infoRow(doc, 'Utilities', agreement.utilitiesIncluded ? 'Included in rent' : 'Not included', col1x, y, halfW);
  infoRow(doc, 'Pet Policy', agreement.petPolicy?.allowed ? `Allowed (deposit: ${fmt.money(agreement.petPolicy?.deposit)})` : 'No pets permitted', col2x, y, halfW);
  y += 32;

  if (agreement.utilitiesDetails) {
    infoRow(doc, 'Utilities Details', agreement.utilitiesDetails, col1x, y, CONTENT_W);
    y += 32;
  }
  if (agreement.terminationPolicy) {
    infoRow(doc, 'Termination Policy', agreement.terminationPolicy, col1x, y, CONTENT_W);
    y += 32;
  }
  y += 8;

  // ── Rent escalation section ──
  if (y > PAGE.height - 150) {
    doc.addPage();
    addPageFurniture(doc, pageNum, '—');
    y = 56;
  }

  y = majorSectionHeading(
    doc,
    '03',
    'RENT ESCALATION',
    'Future rent adjustment schedule and projected amounts.',
    y
  );

  if (agreement.rentEscalation?.enabled) {
    const escalationPct = Number(agreement.rentEscalation?.percentage || 0);
    const currentRent = Number(agreement.financials?.rentAmount || 0);
    const yearOneIncrease = (currentRent * escalationPct) / 100;
    const nextEscalatedRent = currentRent + yearOneIncrease;

    infoRow(doc, 'Escalation Status', 'Enabled', col1x, y, halfW);
    infoRow(doc, 'Annual Increase', `${escalationPct}%`, col2x, y, halfW);
    y += 32;

    infoRow(doc, 'Current Rent', fmt.money(currentRent), col1x, y, halfW);
    infoRow(doc, 'Projected Rent After Escalation', fmt.money(nextEscalatedRent), col2x, y, halfW);
    y += 32;

    infoRow(doc, 'Next Scheduled Escalation', fmt.date(agreement.rentEscalation?.nextScheduledAt), col1x, y, CONTENT_W);
    y += 32;
  } else {
    infoRow(doc, 'Escalation Status', 'Disabled', col1x, y, CONTENT_W);
    y += 32;
  }

  y += 8;

  // ── Standard clauses section ──
  y = majorSectionHeading(
    doc,
    '04',
    'STANDARD CONDITIONS',
    'Base legal conditions that apply throughout the tenancy.',
    y
  );

  const standardClauses = [
    'The Tenant shall keep the property in clean and habitable condition throughout the tenancy.',
    'The Tenant shall not sublet or assign the property without prior written consent from the Landlord.',
    'The Landlord shall provide 24 hours notice before entering the property except in emergencies.',
    'Any damage beyond normal wear and tear shall be deducted from the security deposit.',
    'The Tenant is responsible for minor maintenance and repairs up to $5,000.',
  ];

  standardClauses.forEach((text, i) => {
    if (y > PAGE.height - 120) {
      doc.addPage();
      addPageFurniture(doc, pageNum, '—');
      y = 56;
    }
    doc.save().font(FONT.bold).fontSize(9).fillColor(C.navy)
      .text(`${i + 1}.`, PAGE.margin, y, { lineBreak: false, width: 16 })
      .restore();
    doc.save().font(FONT.regular).fontSize(9).fillColor(C.gray700)
      .text(text, PAGE.margin + 18, y, { width: CONTENT_W - 18 })
      .restore();
    y += doc.heightOfString(text, { width: CONTENT_W - 18 }) + 10;
  });

  y += 8;

  // ════ ADDITIONAL CLAUSES ══════════════════════════════════════════════════
  const agreementWithRefs = Object.assign(
    Object.create(Object.getPrototypeOf(agreement)),
    agreement,
    { landlord, tenant, property }
  );
  const resolvedClauses = substituteClauses(agreementWithRefs);

  if (resolvedClauses.length > 0) {
    if (y > PAGE.height - 160) {
      doc.addPage();
      addPageFurniture(doc, pageNum, '—');
      y = 56;
    }

    y = majorSectionHeading(
      doc,
      '05',
      'ADDITIONAL CLAUSES',
      'Custom clauses selected by the parties are included below and form part of this agreement.',
      y
    );

    resolvedClauses.forEach((clause, i) => {
      const clauseTitle = String(clause.title || `Clause ${i + 1}`);
      const bodyText = String(clause.body || '');
      const innerW = CONTENT_W - 28;
      const clauseLabel = `${i + 1}. ${clauseTitle}`;

      // Measure using the same typography we render with, to avoid overestimation
      // that can create unnecessary near-empty pages.
      doc.save().font(FONT.bold).fontSize(10);
      const titleH = doc.heightOfString(clauseLabel, { width: innerW });
      doc.restore();

      doc.save().font(FONT.regular).fontSize(9);
      const bodyH = doc.heightOfString(bodyText, { width: innerW });
      doc.restore();

      const cardH = Math.max(74, 20 + titleH + bodyH + 24);

      if (y + cardH > PAGE.height - 86) {
        doc.addPage();
        addPageFurniture(doc, pageNum, '—');
        y = 56;
      }

      doc.save().roundedRect(PAGE.margin, y, CONTENT_W, cardH, 7).stroke(C.gray300).restore();
      rect(doc, PAGE.margin, y, CONTENT_W, 22, C.lightBlue);
      doc.save().font(FONT.bold).fontSize(9).fillColor(C.navy)
        .text('ADDITIONAL TERM', PAGE.margin + 10, y + 7, { lineBreak: false })
        .restore();
      y += 30;

      doc.save().font(FONT.bold).fontSize(10).fillColor(C.gray900)
        .text(clauseLabel, PAGE.margin + 14, y, { width: innerW })
        .restore();
      y += titleH + 8;

      doc.save().font(FONT.regular).fontSize(9).fillColor(C.gray700)
        .text(bodyText, PAGE.margin + 14, y, { width: innerW })
        .restore();
      y += bodyH + 14;
    });
  }

  // ════ SIGNATURES PAGE ════════════════════════════════════════════════════
  doc.addPage();
  addPageFurniture(doc, pageNum, '—');
  y = 56;

  y = majorSectionHeading(
    doc,
    '06',
    'DIGITAL SIGNATURES',
    'Each signature below confirms acceptance of all clauses, including additional dynamic clauses.',
    y
  );

  // Status banner
  const bothSigned = agreement.signatures?.landlord?.signed && agreement.signatures?.tenant?.signed;
  const bannerText = bothSigned
    ? 'This agreement is fully executed by all parties.'
    : 'This agreement is pending one or more signatures.';
  rect(doc, PAGE.margin, y, CONTENT_W, 30, C.gray100);
  doc.save().roundedRect(PAGE.margin, y, CONTENT_W, 30, 4).stroke(C.gray300).restore();
  doc.save().font(FONT.bold).fontSize(9).fillColor(C.gray700)
    .text(bannerText, PAGE.margin + 12, y + 10, { lineBreak: false })
    .restore();
  y += 44;

  const sigGap = 16;
  const sigW = (CONTENT_W - sigGap) / 2;
  const sigH = 110;
  signatureBlock(
    doc, 'LANDLORD SIGNATURE',
    landlord,
    agreement.signatures?.landlord?.drawData,
    agreement.signatures?.landlord?.signedAt,
    PAGE.margin, y, sigW, { blockH: sigH }
  );

  signatureBlock(
    doc, 'TENANT SIGNATURE',
    tenant,
    agreement.signatures?.tenant?.drawData,
    agreement.signatures?.tenant?.signedAt,
    PAGE.margin + sigW + sigGap, y, sigW, { blockH: sigH }
  );

  y += sigH + 20;
  hr(doc, y, C.gray300);
  y += 16;

  doc.save().font(FONT.bold).fontSize(10).fillColor(C.gray900)
    .text('E-SIGNATURE ACKNOWLEDGEMENT', PAGE.margin, y, { width: CONTENT_W, align: 'center' })
    .restore();
  y += 14;

  doc.save().font(FONT.regular).fontSize(8).fillColor(C.gray500)
    .text(
      'By signing above, both parties acknowledge that they have read, understood, and agree to all terms and conditions set forth in this Residential Rental Agreement. This document is legally binding upon execution.',
      PAGE.margin, y, { width: CONTENT_W, align: 'center' }
    )
    .restore();
}

// ═════════════════════════════════════════════════════════════════════════════
// RECEIPT PDF
// ═════════════════════════════════════════════════════════════════════════════

function _buildReceiptPDF(doc, payment, tenant, property) {
  const fmt = {
    money: n => `$${Number(n ?? 0).toLocaleString('en-US')}`,
    date: d => d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—',
    month: d => d ? new Date(d).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) : '—',
  };

  // A4 portrait for better professional look
  const W = 595.28, H = 841.89, M = 50, CW = W - M * 2;

  // ── White background ──
  rect(doc, 0, 0, W, H, C.white);

  // ── Header stripe ──
  rect(doc, 0, 0, W, 110, C.navy);

  // Decorative accent circles (purely visual, full opacity)
  doc.save().circle(W + 10, -10, 100).fillOpacity(0.07).fillColor(C.white).fill().restore();
  doc.save().circle(W - 60, 80, 60).fillOpacity(0.05).fillColor(C.white).fill().restore();

  // Brand name
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(22).fillColor(C.white)
    .text('RentifyPro', M, 24, { lineBreak: false })
    .restore();

  // Tagline
  doc.save()
    .fillOpacity(1).font(FONT.regular).fontSize(9).fillColor('#93C5FD')
    .text('Official Rent Payment Receipt', M, 52, { lineBreak: false })
    .restore();

  // Receipt number badge (right side)
  const receiptLabel = `RECEIPT  #${payment.receiptNumber || String(payment._id).slice(-8).toUpperCase()}`;
  const rLabelW = doc.widthOfString(receiptLabel, { font: FONT.bold, fontSize: 9 }) + 24;
  rect(doc, W - M - rLabelW, 30, rLabelW, 22, '#1D4ED8');
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(9).fillColor(C.white)
    .text(receiptLabel, W - M - rLabelW + 12, 36, { lineBreak: false })
    .restore();

  // Payment type badge below receipt number
  const typeLabel = (payment.type || 'rent').replace(/_/g, ' ').toUpperCase();
  badge(doc, typeLabel, W - M - 80, 58, C.teal);

  // ── Amount Hero block ──
  let y = 128;
  rect(doc, M, y, CW, 80, '#F0F7FF');
  rect(doc, M, y, 5, 80, C.blue);
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(9).fillColor(C.blue)
    .text('TOTAL AMOUNT PAID', M + 18, y + 14, { lineBreak: false })
    .restore();
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(30).fillColor(C.navy)
    .text(fmt.money(payment.amount), M + 18, y + 30, { lineBreak: false })
    .restore();

  // PAID stamp (right side of amount box)
  rect(doc, W - M - 90, y + 20, 78, 36, '#D1FAE5');
  rect(doc, W - M - 90, y + 20, 4, 36, C.green);
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(16).fillColor(C.green)
    .text('✓ PAID', W - M - 80, y + 30, { lineBreak: false })
    .restore();

  y += 98;

  // ── Two-column detail section ──
  const colW = (CW - 16) / 2;

  // Left column — Payment Details
  sectionHeading(doc, 'PAYMENT DETAILS', y);
  y += 32;

  const leftRows = [
    { label: 'Payment Date', value: fmt.date(payment.paidAt || payment.createdAt) },
    { label: 'Period Covered', value: fmt.month(payment.dueDate) },
    { label: 'Payment Method', value: 'Stripe (Card)' },
    ...(payment.stripePaymentIntent ? [{ label: 'Transaction ID', value: payment.stripePaymentIntent.slice(0, 22) + '…' }] : []),
    ...(payment.lateFeeIncluded && payment.lateFeeAmount > 0 ? [{ label: 'Late Fee', value: fmt.money(payment.lateFeeAmount) }] : []),
  ];

  const startY = y;
  leftRows.forEach((row, i) => {
    const bg = i % 2 === 0 ? C.white : C.gray100;
    rect(doc, M, y, colW, 26, bg);
    doc.save()
      .fillOpacity(1).font(FONT.bold).fontSize(7.5).fillColor(C.gray500)
      .text(row.label, M + 10, y + 9, { lineBreak: false, width: colW * 0.44 })
      .restore();
    doc.save()
      .fillOpacity(1).font(FONT.regular).fontSize(8.5).fillColor(C.gray900)
      .text(String(row.value), M + colW * 0.46, y + 8, { lineBreak: false, width: colW * 0.52 })
      .restore();
    y += 26;
  });

  // Right column — Property & Tenant
  const rightX = M + colW + 16;
  let ry = startY;

  // Property & tenant header
  rect(doc, rightX, ry - 32, colW, 24, C.lightBlue);
  rect(doc, rightX, ry - 32, 4, 24, C.blue);
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(9).fillColor(C.navy)
    .text('PROPERTY & TENANT', rightX + 12, ry - 24, { lineBreak: false })
    .restore();

  const fullAddress = property?.address
    ? [
        property.address.street,
        property.address.unitNumber ? `Unit ${property.address.unitNumber}` : '',
        property.address.city,
        property.address.state,
        property.address.country,
      ].filter(Boolean).join(', ')
    : '—';

  const rightRows = [
    { label: 'Tenant', value: tenant?.name || '—' },
    { label: 'Email', value: tenant?.email || '—' },
    { label: 'Property', value: property?.title || '—' },
    { label: 'Address', value: fullAddress },
    { label: 'Receipt No.', value: `#${payment.receiptNumber || '—'}` },
  ];

  rightRows.forEach((row, i) => {
    const bg = i % 2 === 0 ? C.white : C.gray100;
    rect(doc, rightX, ry, colW, 26, bg);
    doc.save()
      .fillOpacity(1).font(FONT.bold).fontSize(7.5).fillColor(C.gray500)
      .text(row.label, rightX + 10, ry + 9, { lineBreak: false, width: colW * 0.4 })
      .restore();
    doc.save()
      .fillOpacity(1).font(FONT.regular).fontSize(8).fillColor(C.gray900)
      .text(String(row.value), rightX + colW * 0.44, ry + 8, { lineBreak: false, width: colW * 0.54 })
      .restore();
    ry += 26;
  });

  // Advance y past both columns
  y = Math.max(y, ry) + 20;

  hr(doc, y, C.gray300, M, CW);
  y += 18;

  // ── Notes / legal disclaimer box ──
  rect(doc, M, y, CW, 48, C.gray100);
  rect(doc, M, y, 4, 48, C.gray500);
  doc.save()
    .fillOpacity(1).font(FONT.bold).fontSize(8).fillColor(C.gray700)
    .text('IMPORTANT:', M + 14, y + 8, { lineBreak: false })
    .restore();
  doc.save()
    .fillOpacity(1).font(FONT.regular).fontSize(7.5).fillColor(C.gray500)
    .text(
      'This receipt confirms that the payment shown above has been received and processed. Please retain this document for your personal records and tax purposes. This receipt does not waive any other obligations under the lease agreement.',
      M + 14, y + 22, { width: CW - 28, lineBreak: true }
    )
    .restore();

  y += 64;

  // ── Signature lines ──
  hr(doc, y + 4, C.gray300, M, (CW / 2) - 10);
  hr(doc, y + 4, C.gray300, M + (CW / 2) + 10, (CW / 2) - 10);
  doc.save()
    .fillOpacity(1).font(FONT.regular).fontSize(7.5).fillColor(C.gray500)
    .text('Landlord / Authorised Signatory', M, y + 10, { lineBreak: false })
    .text('Tenant Acknowledgement', M + (CW / 2) + 10, y + 10, { lineBreak: false })
    .restore();

  // ── Footer ──
  rect(doc, 0, H - 40, W, 40, C.navy);
  doc.save()
    .fillOpacity(1).font(FONT.regular).fontSize(7.5).fillColor('#93C5FD')
    .text(
      `Generated by RentifyPro  •  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}  •  This is a system-generated receipt and does not require a physical signature to be valid.`,
      M, H - 23, { align: 'center', lineBreak: false, width: CW }
    )
    .restore();
}

// ─── Public API ───────────────────────────────────────────────────────────────

const generateAgreementPDF = (agreement, landlord, tenant, property, res) => {
  const doc = new PDFDocument({
    margin: PAGE.margin,
    size: 'A4',
    autoFirstPage: true,
    bufferPages: true,
  });
  doc.pipe(res);
  _buildPDF(doc, agreement, landlord, tenant, property);
  finalizeAgreementPagination(doc, 'RENTAL AGREEMENT');
  doc.flushPages();
  doc.end();
};

const generateAgreementPDFBuffer = (agreement, landlord, tenant, property) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: PAGE.margin,
      size: 'A4',
      autoFirstPage: true,
      bufferPages: true,
    });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    _buildPDF(doc, agreement, landlord, tenant, property);
    finalizeAgreementPagination(doc, 'RENTAL AGREEMENT');
    doc.flushPages();
    doc.end();
  });
};

const generateReceiptPDF = (payment, tenant, property, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4', autoFirstPage: true });
  doc.pipe(res);
  _buildReceiptPDF(doc, payment, tenant, property);
  doc.end();
};

const generateReceiptPDFBuffer = (payment, tenant, property) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4', autoFirstPage: true });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    _buildReceiptPDF(doc, payment, tenant, property);
    doc.end();
  });
};

module.exports = {
  generateAgreementPDF,
  generateAgreementPDFBuffer,
  generateReceiptPDF,
  generateReceiptPDFBuffer,
};