const mongoose = require('mongoose');
const dotenv = require('dotenv');
const PdfTheme = require('../models/PdfTheme');

const path = require('path');

// Determine env file based on environment
const envFile = process.env.NODE_ENV === 'production' ? '.env.production' : '.env';
dotenv.config({ path: path.join(__dirname, '..', envFile) });

/**
 * Visual themes matching the frontend VISUAL_THEMES registry.
 * Each theme's `themeSlug` must match the frontend `id` exactly.
 */
const themes = [
  // ─── 1. Clean Slate ─────────────────────────────────────────────────
  {
    name: 'Clean Slate',
    themeSlug: 'clean-slate',
    description: 'Full-width single column, no frills — tables get maximum space.',
    primaryColor: '#1E293B',
    accentColor: '#3B82F6',
    backgroundColor: '#FFFFFF',
    pageBackgroundColor: '#FFFFFF',
    headingColor: '#0F172A',
    bodyTextColor: '#475569',
    fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
    headingFontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap',
    tableBorderColor: '#E2E8F0',
    tableHeaderBg: '#F8FAFC',
    tableHeaderTextColor: '#1E293B',
    heroBackground: 'transparent',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '80px',
    logoAlignment: 'left',
    tableRadius: '8px',
    pageTexture: 'none',
    headerRule: '3px solid #3B82F6',
    sectionRule: '1px solid #E2E8F0',
    layoutStyle: 'full-width',
    headerStyle: 'minimal',
    tableZone: 'full',
    maxComfortableTableCols: 8,
    sidebarSections: [],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 2. Executive Sidebar ───────────────────────────────────────────
  {
    name: 'Executive Sidebar',
    themeSlug: 'executive-sidebar',
    description: 'Dark navy sidebar with party info, dates & financials. Main body for text & tables.',
    primaryColor: '#1B2A4A',
    accentColor: '#C5A55A',
    backgroundColor: '#FAF8F4',
    pageBackgroundColor: '#FAF8F4',
    headingColor: '#1B2A4A',
    bodyTextColor: '#2D3748',
    fontFamily: "'Lora', 'Times New Roman', serif",
    headingFontFamily: "'Playfair Display', Georgia, serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Lora:wght@400;600;700&display=swap',
    tableBorderColor: '#C5A55A',
    tableHeaderBg: '#1B2A4A',
    tableHeaderTextColor: '#F5DFA0',
    heroBackground: '#F2EDE3',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '60px',
    logoAlignment: 'center',
    tableRadius: '0px',
    pageTexture: 'none',
    headerRule: '4px double #C5A55A',
    sectionRule: '1px solid #D4BC8A',
    layoutStyle: 'sidebar-left',
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'main',
    maxComfortableTableCols: 4,
    sidebarSections: ['parties', 'dates', 'financials'],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 3. Modern Split ────────────────────────────────────────────────
  {
    name: 'Modern Split',
    themeSlug: 'modern-split',
    description: 'Full-width header band, two-column info strip, then single-column body.',
    primaryColor: '#0F172A',
    accentColor: '#6366F1',
    backgroundColor: '#FFFFFF',
    pageBackgroundColor: '#FFFFFF',
    headingColor: '#0F172A',
    bodyTextColor: '#334155',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    headingFontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@600;700;800;900&family=DM+Sans:wght@400;500;600;700&display=swap',
    tableBorderColor: '#E2E8F0',
    tableHeaderBg: '#0F172A',
    tableHeaderTextColor: '#FFFFFF',
    heroBackground: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
    heroPattern: 'none',
    heroHeight: 180,
    logoMaxHeight: '50px',
    logoAlignment: 'left',
    tableRadius: '8px',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '2px solid #E2E8F0',
    layoutStyle: 'split-header',
    headerStyle: 'split',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates'],
    isGlobal: true,
    isDefault: true,
  },

  // ─── 4. Legal Folio ─────────────────────────────────────────────────
  {
    name: 'Legal Folio',
    themeSlug: 'legal-folio',
    description: 'Narrow centered body with generous margins, formal serif typography.',
    primaryColor: '#1A1A2E',
    accentColor: '#8B2635',
    backgroundColor: '#FDFCFA',
    pageBackgroundColor: '#FDFCFA',
    headingColor: '#0F1419',
    bodyTextColor: '#2D3748',
    fontFamily: "'Source Sans 3', 'Segoe UI', Roboto, sans-serif",
    headingFontFamily: "'Merriweather', Georgia, serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@700;900&family=Source+Sans+3:wght@400;600;700&display=swap',
    tableBorderColor: '#C8B8A8',
    tableHeaderBg: '#1A1A2E',
    tableHeaderTextColor: '#E8D5C4',
    heroBackground: 'transparent',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '70px',
    logoAlignment: 'center',
    tableRadius: '0px',
    pageTexture: 'repeating-linear-gradient(0deg, transparent, transparent 27px, rgba(0,0,0,0.03) 27px, rgba(0,0,0,0.03) 28px)',
    headerRule: '4px double #8B2635',
    sectionRule: '1px solid #D6CFD3',
    layoutStyle: 'centered-narrow',
    bodyMaxWidthPx: 580,
    headerStyle: 'minimal',
    tableZone: 'full',
    maxComfortableTableCols: 5,
    sidebarSections: [],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 5. Corporate Brief ────────────────────────────────────────────
  {
    name: 'Corporate Brief',
    themeSlug: 'corporate-brief',
    description: 'Accent sidebar on the right with key terms. Main body on left for text & tables.',
    primaryColor: '#2D1B4E',
    accentColor: '#D4A574',
    backgroundColor: '#FEFCFF',
    pageBackgroundColor: '#FEFCFF',
    headingColor: '#2D1B4E',
    bodyTextColor: '#4A3F5C',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    headingFontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@600;700;800;900&family=DM+Sans:wght@400;500;600;700&display=swap',
    tableBorderColor: '#E8D5C4',
    tableHeaderBg: '#2D1B4E',
    tableHeaderTextColor: '#FFFFFF',
    heroBackground: 'transparent',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '8px',
    pageTexture: 'none',
    headerRule: '4px solid #D4A574',
    sectionRule: '1px dashed #E8D5C4',
    layoutStyle: 'sidebar-right',
    sidebarWidthPx: 200,
    mainContentWidthPx: 594,
    headerStyle: 'inline',
    tableZone: 'main',
    maxComfortableTableCols: 4,
    sidebarSections: ['parties', 'financials', 'policies'],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 6. Bold Statement ─────────────────────────────────────────────
  {
    name: 'Bold Statement',
    themeSlug: 'bold-statement',
    description: 'Large gradient hero band (40% of page), compact body below — everything full-width.',
    primaryColor: '#0F766E',
    accentColor: '#F97066',
    backgroundColor: '#FFFFFF',
    pageBackgroundColor: '#F0FDFA',
    headingColor: '#134E4A',
    bodyTextColor: '#334155',
    fontFamily: "'Nunito', 'Segoe UI', sans-serif",
    headingFontFamily: "'Poppins', 'Helvetica Neue', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@600;700;800;900&family=Nunito:wght@400;600;700&display=swap',
    tableBorderColor: '#2DD4BF',
    tableHeaderBg: '#0F766E',
    tableHeaderTextColor: '#FFFFFF',
    heroBackground: 'linear-gradient(160deg, #0F766E 0%, #0D9488 50%, #2DD4BF 100%)',
    heroPattern: 'none',
    heroHeight: 320,
    logoMaxHeight: '60px',
    logoAlignment: 'center',
    tableRadius: '10px',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '2px solid #CCFBF1',
    layoutStyle: 'top-band',
    headerStyle: 'banner',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: [],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 7. Dual Panel ──────────────────────────────────────────────────
  {
    name: 'Dual Panel',
    themeSlug: 'dual-panel',
    description: 'After a header, body splits into two equal columns. Tables break across both.',
    primaryColor: '#111111',
    accentColor: '#9B8467',
    backgroundColor: '#FFFFFF',
    pageBackgroundColor: '#FAF9F6',
    headingColor: '#111111',
    bodyTextColor: '#3D3D3D',
    fontFamily: "'Lora', 'Georgia', serif",
    headingFontFamily: "'Cinzel', 'Playfair Display', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700;800;900&family=Lora:wght@400;600;700&display=swap',
    tableBorderColor: '#C5B5A5',
    tableHeaderBg: '#F5F2ED',
    tableHeaderTextColor: '#111111',
    heroBackground: 'transparent',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '60px',
    logoAlignment: 'center',
    tableRadius: '0px',
    pageTexture: 'none',
    headerRule: '2px solid #9B8467',
    sectionRule: '1px dotted #C5B5A5',
    layoutStyle: 'two-column-body',
    headerStyle: 'minimal',
    tableZone: 'full',
    maxComfortableTableCols: 5,
    sidebarSections: [],
    isGlobal: true,
    isDefault: false,
  },

  // ─── 8. Infographic ─────────────────────────────────────────────────
  {
    name: 'Infographic',
    themeSlug: 'infographic',
    description: '60/40 asymmetric split — body text left, key terms right. Tables break across both.',
    primaryColor: '#0A0A0A',
    accentColor: '#2563EB',
    backgroundColor: '#FFFFFF',
    pageBackgroundColor: '#FFFFFF',
    headingColor: '#000000',
    bodyTextColor: '#1F2937',
    fontFamily: "'Roboto', 'Helvetica Neue', sans-serif",
    headingFontFamily: "'Space Grotesk', 'Courier New', monospace",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@600;700;800;900&family=Roboto:wght@400;500;700&display=swap',
    tableBorderColor: '#D1D5DB',
    tableHeaderBg: '#0A0A0A',
    tableHeaderTextColor: '#FFFFFF',
    heroBackground: 'transparent',
    heroPattern: 'none',
    heroHeight: 0,
    logoMaxHeight: '50px',
    logoAlignment: 'left',
    tableRadius: '0px',
    pageTexture: 'none',
    headerRule: '4px solid #2563EB',
    sectionRule: '2px solid #E5E7EB',
    layoutStyle: 'asymmetric',
    leftWidthPercent: 60,
    rightWidthPercent: 40,
    headerStyle: 'minimal',
    tableZone: 'full',
    maxComfortableTableCols: 5,
    sidebarSections: ['parties', 'dates', 'financials', 'policies'],
    isGlobal: true,
    isDefault: false,
  },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/rentifypro';
    console.log(`Connecting to MongoDB at ${mongoUri}`);
    await mongoose.connect(mongoUri);

    console.log('Clearing existing global themes...');
    await PdfTheme.deleteMany({ isGlobal: true });

    console.log('Inserting visual themes...');
    const createdThemes = await PdfTheme.insertMany(themes);
    
    console.log('Successfully inserted visual themes:');
    createdThemes.forEach(t => console.log(` - ${t.name} [${t.themeSlug}] (layout: ${t.layoutStyle})`));

  } catch (error) {
    console.error('Error seeding themes:', error);
  } finally {
    mongoose.connection.close();
    console.log('Database connection closed.');
  }
}

seed();