const mongoose = require('mongoose');
const dotenv = require('dotenv');
const PdfTheme = require('../models/PdfTheme');

const path = require('path');

// Determine env file based on environment
const envFile = process.env.NODE_ENV === 'production' ? '.env.production' : '.env';
dotenv.config({ path: path.join(__dirname, '..', envFile) });

/**
 * Visual themes matching the frontend VISUAL_THEMES registry.
 * Each theme's `themeSlug` must match the frontend `id` exactly.
 */
const themes = [

  {
    name: 'Classic Chronological',
    description: 'A top-to-bottom stack: safe, ATS-friendly, works for any industry.',
    themeSlug: 'classic-single',
    primaryColor: '#1F2937',
    accentColor: '#3B82F6',
    backgroundColor: '#FFFFFF',
    headingColor: '#1F2937',
    bodyTextColor: '#334155',
    tableBorderColor: '#3B82F6',
    tableHeaderBg: '#1F2937',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Inter', sans-serif",
    headingFontFamily: "'Inter', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Inter" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#1F2937',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #3B82F6',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#1F2937',
    layoutStyle: 'full-width',
    isGlobal: true,
    isDefault: true,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#1F2937',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Modern Left Rail',
    description: 'Narrow left column holds contact and metadata. Wide right column holds main text.',
    themeSlug: 'sidebar-left',
    primaryColor: '#0F172A',
    accentColor: '#10B981',
    backgroundColor: '#FFFFFF',
    headingColor: '#0F172A',
    bodyTextColor: '#334155',
    tableBorderColor: '#10B981',
    tableHeaderBg: '#0F172A',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Open Sans', sans-serif",
    headingFontFamily: "'Montserrat', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Montserrat" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#0F172A',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #10B981',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#0F172A',
    layoutStyle: 'sidebar-left',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 4,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#0F172A',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Editorial Right Rail',
    description: 'Main content on the left, sidebar on the right. Eye lands on experience first.',
    themeSlug: 'sidebar-right',
    primaryColor: '#374151',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFFFF',
    headingColor: '#374151',
    bodyTextColor: '#334155',
    tableBorderColor: '#F59E0B',
    tableHeaderBg: '#374151',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Lato', sans-serif",
    headingFontFamily: "'Merriweather', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Merriweather" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#374151',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #F59E0B',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#374151',
    layoutStyle: 'sidebar-right',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 4,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#374151',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Executive Header',
    description: 'Full-width colored header band with key info. Clean one-column body below.',
    themeSlug: 'top-band',
    primaryColor: '#1E3A8A',
    accentColor: '#60A5FA',
    backgroundColor: '#FFFFFF',
    headingColor: '#1E3A8A',
    bodyTextColor: '#334155',
    tableBorderColor: '#60A5FA',
    tableHeaderBg: '#1E3A8A',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Roboto', sans-serif",
    headingFontFamily: "'Oswald', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Oswald" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#1E3A8A',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #60A5FA',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#1E3A8A',
    layoutStyle: 'top-band',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'banner',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#1E3A8A',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Functional Focus',
    description: 'Highlights key functional metrics grouped by category before chronologies.',
    themeSlug: 'functional',
    primaryColor: '#111827',
    accentColor: '#8B5CF6',
    backgroundColor: '#FFFFFF',
    headingColor: '#111827',
    bodyTextColor: '#334155',
    tableBorderColor: '#8B5CF6',
    tableHeaderBg: '#111827',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Nunito', sans-serif",
    headingFontFamily: "'Poppins', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Poppins" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#111827',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #8B5CF6',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#111827',
    layoutStyle: 'full-width',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#111827',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Hybrid Combination',
    description: 'Header, split metadata grid, then detailed reverse-chronological content.',
    themeSlug: 'hybrid',
    primaryColor: '#064E3B',
    accentColor: '#34D399',
    backgroundColor: '#FFFFFF',
    headingColor: '#064E3B',
    bodyTextColor: '#334155',
    tableBorderColor: '#34D399',
    tableHeaderBg: '#064E3B',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Source Sans Pro', sans-serif",
    headingFontFamily: "'Playfair Display', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "PlayfairDisplay" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#064E3B',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #34D399',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#064E3B',
    layoutStyle: 'split-header',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#064E3B',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Progression Timeline',
    description: 'A vertical line runs down the page visually emphasizing progression.',
    themeSlug: 'timeline',
    primaryColor: '#312E81',
    accentColor: '#A78BFA',
    backgroundColor: '#FFFFFF',
    headingColor: '#312E81',
    bodyTextColor: '#334155',
    tableBorderColor: '#A78BFA',
    tableHeaderBg: '#312E81',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Work Sans', sans-serif",
    headingFontFamily: "'Raleway', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Raleway" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#312E81',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #A78BFA',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#312E81',
    layoutStyle: 'timeline',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#312E81',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Grid Dashboard',
    description: 'Page divided into rectangular cards. Feels like a dashboard portfolio.',
    themeSlug: 'grid-modular',
    primaryColor: '#171717',
    accentColor: '#F43F5E',
    backgroundColor: '#FFFFFF',
    headingColor: '#171717',
    bodyTextColor: '#334155',
    tableBorderColor: '#F43F5E',
    tableHeaderBg: '#171717',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Inter', sans-serif",
    headingFontFamily: "'Space Grotesk', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "SpaceGrotesk" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#171717',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #F43F5E',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#171717',
    layoutStyle: 'grid-modular',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#171717',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Creative Infographic',
    description: 'Heavy use of visuals, charts, and pictograms for high impact.',
    themeSlug: 'infographic',
    primaryColor: '#4C1D95',
    accentColor: '#FBBF24',
    backgroundColor: '#FFFFFF',
    headingColor: '#4C1D95',
    bodyTextColor: '#334155',
    tableBorderColor: '#FBBF24',
    tableHeaderBg: '#4C1D95',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Ubuntu', sans-serif",
    headingFontFamily: "'Ubuntu', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Ubuntu" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#4C1D95',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #FBBF24',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#4C1D95',
    layoutStyle: 'infographic',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#4C1D95',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Magazine Feature',
    description: 'Two-column body with serif headlines, generous whitespace, pull-quotes.',
    themeSlug: 'editorial',
    primaryColor: '#000000',
    accentColor: '#D97706',
    backgroundColor: '#FFFFFF',
    headingColor: '#000000',
    bodyTextColor: '#334155',
    tableBorderColor: '#D97706',
    tableHeaderBg: '#000000',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'PT Serif', serif",
    headingFontFamily: "'Lora', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Lora" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#000000',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #D97706',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#000000',
    layoutStyle: 'two-column-body',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'main',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#000000',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Swiss Minimalist',
    description: 'Lots of whitespace, strict typographic hierarchy. No dividers, just space.',
    themeSlug: 'minimalist',
    primaryColor: '#262626',
    accentColor: '#525252',
    backgroundColor: '#FFFFFF',
    headingColor: '#262626',
    bodyTextColor: '#334155',
    tableBorderColor: '#525252',
    tableHeaderBg: '#262626',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Helvetica Neue', sans-serif",
    headingFontFamily: "'Helvetica Neue', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "HelveticaNeue" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#262626',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #525252',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#262626',
    layoutStyle: 'full-width',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#262626',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Academic Standard',
    description: 'Dense, plain typography. Multi-page capable, formal structure.',
    themeSlug: 'academic',
    primaryColor: '#000000',
    accentColor: '#000000',
    backgroundColor: '#FFFFFF',
    headingColor: '#000000',
    bodyTextColor: '#334155',
    tableBorderColor: '#000000',
    tableHeaderBg: '#000000',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Times New Roman', serif",
    headingFontFamily: "'Times New Roman', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "TimesNewRoman" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#000000',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #000000',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#000000',
    layoutStyle: 'full-width',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#000000',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Federal Government',
    description: 'Prose-heavy, strict format requirements. Single column, utilitarian design.',
    themeSlug: 'federal',
    primaryColor: '#1E293B',
    accentColor: '#0F172A',
    backgroundColor: '#FFFFFF',
    headingColor: '#1E293B',
    bodyTextColor: '#334155',
    tableBorderColor: '#0F172A',
    tableHeaderBg: '#1E293B',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Courier New', monospace",
    headingFontFamily: "'Courier New', monospace",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "CourierNew" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#1E293B',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #0F172A',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#1E293B',
    layoutStyle: 'full-width',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#1E293B',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Portfolio Integrated',
    description: 'Visual-heavy layout bridging text and large thumbnail spaces.',
    themeSlug: 'portfolio',
    primaryColor: '#27272A',
    accentColor: '#14B8A6',
    backgroundColor: '#FFFFFF',
    headingColor: '#27272A',
    bodyTextColor: '#334155',
    tableBorderColor: '#14B8A6',
    tableHeaderBg: '#27272A',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Epilogue', sans-serif",
    headingFontFamily: "'Syne', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Syne" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#27272A',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #14B8A6',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#27272A',
    layoutStyle: 'portfolio',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#27272A',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Business Card Header',
    description: 'Top mimics a business card in a bordered box, followed by standard content.',
    themeSlug: 'card-header',
    primaryColor: '#450A0A',
    accentColor: '#EF4444',
    backgroundColor: '#FFFFFF',
    headingColor: '#450A0A',
    bodyTextColor: '#334155',
    tableBorderColor: '#EF4444',
    tableHeaderBg: '#450A0A',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Faustina', serif",
    headingFontFamily: "'Cinzel', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Cinzel" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#450A0A',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #EF4444',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#450A0A',
    layoutStyle: 'card-header',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#450A0A',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Split-Screen 50/50',
    description: 'Page divided into two equal halves. Symmetrical, modern, magazine-like.',
    themeSlug: 'split-screen',
    primaryColor: '#022C22',
    accentColor: '#10B981',
    backgroundColor: '#FFFFFF',
    headingColor: '#022C22',
    bodyTextColor: '#334155',
    tableBorderColor: '#10B981',
    tableHeaderBg: '#022C22',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Proza Libre', sans-serif",
    headingFontFamily: "'Cormorant Garamond', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "CormorantGaramond" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#022C22',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #10B981',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#022C22',
    layoutStyle: 'split-screen',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 4,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#022C22',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Three-Column Dense',
    description: 'Narrow columns for metadata with text spanning multiple columns.',
    themeSlug: 'three-column',
    primaryColor: '#082F49',
    accentColor: '#0EA5E9',
    backgroundColor: '#FFFFFF',
    headingColor: '#082F49',
    bodyTextColor: '#334155',
    tableBorderColor: '#0EA5E9',
    tableHeaderBg: '#082F49',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'PT Sans', sans-serif",
    headingFontFamily: "'Oswald', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Oswald" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#082F49',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #0EA5E9',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#082F49',
    layoutStyle: 'three-column',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#082F49',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Banner with Photo Circle',
    description: 'Wide top banner with a circular portrait/logo overlay.',
    themeSlug: 'banner-circle',
    primaryColor: '#4A044E',
    accentColor: '#D946EF',
    backgroundColor: '#FFFFFF',
    headingColor: '#4A044E',
    bodyTextColor: '#334155',
    tableBorderColor: '#D946EF',
    tableHeaderBg: '#4A044E',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Quicksand', sans-serif",
    headingFontFamily: "'Quicksand', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "Quicksand" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#4A044E',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #D946EF',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#4A044E',
    layoutStyle: 'banner-circle',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'banner',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#4A044E',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Project-First Showcase',
    description: 'Header immediately followed by key projects and metrics.',
    themeSlug: 'project-first',
    primaryColor: '#172554',
    accentColor: '#3B82F6',
    backgroundColor: '#FFFFFF',
    headingColor: '#172554',
    bodyTextColor: '#334155',
    tableBorderColor: '#3B82F6',
    tableHeaderBg: '#172554',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'Fira Sans', sans-serif",
    headingFontFamily: "'Fira Sans', sans-serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "FiraSans" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#172554',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #3B82F6',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#172554',
    layoutStyle: 'top-band',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'banner',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#172554',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
  {
    name: 'Narrative Story',
    description: 'Written as prose. Central focused column for personal statement reading.',
    themeSlug: 'narrative',
    primaryColor: '#2E1065',
    accentColor: '#8B5CF6',
    backgroundColor: '#FFFFFF',
    headingColor: '#2E1065',
    bodyTextColor: '#334155',
    tableBorderColor: '#8B5CF6',
    tableHeaderBg: '#2E1065',
    tableHeaderTextColor: '#FFFFFF',
    fontFamily: "'EB Garamond', serif",
    headingFontFamily: "'EB Garamond', serif",
    googleFontUrl: 'https://fonts.googleapis.com/css2?family=' + "EBGaramond" + ':wght@400;700&display=swap',
    fontSizeScale: 1.0,
    heroBackground: '#2E1065',
    heroPattern: 'none',
    pageTexture: 'none',
    headerRule: 'none',
    sectionRule: '1px solid #8B5CF6',
    watermarkEnabled: false,
    watermarkText: '',
    watermarkOpacity: 0.05,
    watermarkColor: '#2E1065',
    layoutStyle: 'centered-narrow',
    isGlobal: true,
    isDefault: false,
    isReceiptDefault: false,
    sidebarWidthPx: 220,
    mainContentWidthPx: 574,
    headerStyle: 'inline',
    tableZone: 'full',
    maxComfortableTableCols: 6,
    sidebarSections: ['parties', 'dates', 'financials'],
    leftWidthPercent: 50,
    rightWidthPercent: 50,
    bodyMaxWidthPx: 600,
    heroHeight: 160,
    heroBgColor: '#2E1065',
    logoMaxHeight: '60px',
    logoAlignment: 'left',
    tableRadius: '4px',
    tableAltRowBg: '#F8FAFC',
    pageBackgroundColor: '#FFFFFF',
  },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/rentifypro';
    console.log(`Connecting to MongoDB at ${mongoUri}`);
    await mongoose.connect(mongoUri);

    console.log('Clearing existing global themes...');
    await PdfTheme.deleteMany({ isGlobal: true });

    console.log('Inserting visual themes...');
    const createdThemes = await PdfTheme.insertMany(themes);
    
    console.log('Successfully inserted visual themes:');
    createdThemes.forEach(t => console.log(` - ${t.name} [${t.themeSlug}] (layout: ${t.layoutStyle})`));

  } catch (error) {
    console.error('Error seeding themes:', error);
  } finally {
    mongoose.connection.close();
    console.log('Database connection closed.');
  }
}

seed();